---
title: "week2 lecture git"
author: "Wang Tingyu Kelly"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in data

```{r}
df = readRDS("data/wk2_stocks.rds")
str(df)
```

## Statistics on returns

```{r}
sum(df$SPY_returns) * 100
mean(df$SPY_returns) * 100
sd(df$SPY_returns) * 100
```
+ The cumulative returns of the S&P index during this period is `r round(sum(df$SPY_returns) * 100, 2)`%.
+ The average daily returns of the S&P index during this period is `r round(mean(df$SPY_returns) * 100, 2)`%.
+ The standard deviation of the daily returns of the S&P index during this period is `r round(sd(df$SPY_returns) * 100, 2)`%. 

## S&P Prices

```{r message = FALSE}
library(tidyverse)
ggplot(data = df, aes(x = date, y = SPY_prices)) +
  geom_line()
```

## S&P Yearly Returns

```{r}
df %>%
  mutate(year = year(date)) %>%
  filter(year != 2024) %>%
  group_by(year) %>%
  summarize(yr_return = sum(SPY_returns) * 100) %>%
  ggplot(aes(x = year, y = yr_return)) +
  geom_col()
```



